### ISSUE TITLE
Rocket failed to launch due to an I/O error. thread 'main' panicked at 'Permission denied (os error 13)

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#10]
after adding login right to the user into the postgresql database i am stuck here now:

```
sudo -u ff-node-monitor RUST_BACKTRACE=1 /var/lib/ff-node-monitor/src/target/release/ff-node-monitor       
🔧
    => address: 127.0.0.1
    => port: 80
    => log: normal
    => workers: 2
    => secret key: provided
    => limits: forms = 32KiB
    => tls: disabled
    => [extra] ff-node-monitor: { secrets = { action_signing_key = "xxxxx", postgres_url = "postgres://ff-node-monitor@/ff-node-monitor" }, ui = { email_from = "freifunk@myserver.de", instance_name = "Freifunk Kiel" }, urls = { nodes = "https://map.freifunk.in-kiel.de/yanic/nodes.json", root = "http://localhost" } }
🛰  Mounting '/':
    => GET /
    => GET /list?<form>
    => GET /list
    => POST /prepare_action
    => GET /run_action?<form>
    => GET /cron
    => GET /static/<file..>
Error: Rocket failed to launch due to an I/O error.
thread 'main' panicked at 'Permission denied (os error 13)', /var/lib/ff-node-monitor/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.3.12/src/error.rs:204:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:413
   7: <rocket::error::LaunchError as core::ops::drop::Drop>::drop
   8: ff_node_monitor::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  13: main
  14: __libc_start_main
  15: <unknown>
```

I use the nightly version you added and this Rocket.toml:

```
[global.ff-node-monitor.ui]
# The name of your Freifunk community.
instance_name = "Freifunk Kiel"
# The sender address of the emails that are sent by ff-node-monitor.  Make sure
# you have a mail service running locally that is set up to deliver emails from
# that address.
email_from = "freifunk@myserver.de"

[global.ff-node-monitor.urls]
# The root URL where you will be hosting ff-node-monitor.
root = "http://localhost"
# The URL to the hopglass nodes.json file.
nodes = "https://map.freifunk.in-kiel.de/yanic/nodes.json"

[global.ff-node-monitor.secrets]
# PostgreSQL credentials.  If you followed the instructions in the README, this
# should be correct.
postgres_url = "postgres://ff-node-monitor@/ff-node-monitor"
# Key used to sign data for confirmation emails.  Generate this key with
# `openssl rand -hex 32`.
action_signing_key = "xxxxx"

[global]
# The address and port on which ff-node-monitor will listen.
address = "127.0.0.1"
port = 80
# Secret key used by Rocket.  Generate this key with `openssl rand -base64 32`.
secret_key = "xxxx/ZqsfLpRSw="
```

**Comment by rubo77** [comment]
maybe you can post your working Rocket.toml? 

We can also chat via Matrix: @rubo77:matrix.eclabs.de Or IRC hackint #ffki

**Comment by rubo77** [comment]
This error is fixed if you select a port above 1000.

use port 8080 for instance and the monitor starts just fine.

**Comment by RalfJung** [comment]
Indeed, ports less than 1024 are reserved on Linux and can only be opened by root. I will add a comment saying so to the docs.

**Comment by rubo77** [comment]
Maybe you can also redirect the low port to a high port and listen on the high port:

    iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080

**Comment by RalfJung** [comment]
Yeah, that's another possibility.

I usually used something like
```
iptables -A PREROUTING -d $IP -p tcp -m tcp --dport 80 -j DNAT --to-destination $IP:8080
-A OUTPUT -d $IP -p tcp -m tcp --dport 80 -j DNAT --to-destination $IP:8053
```
I think with just a `REDIRECT`, the answers will come from the wrong port.
