### ISSUE TITLE
error after fresh install on Debian 8.11

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#47]
```
$ RUST_BACKTRACE=1 /opt/ff-node-monitor/src/target/release/ff-node-monitor
🔧  Configured for development.
    => address: 0.0.0.0
    => port: 8833
    => log: normal
    => workers: 2
    => secret key: provided
    => limits: forms = 32KiB
    => tls: disabled
    => [extra] ff-node-monitor: { secrets = { action_signing_key = "...", postgres_url = "postgres://ff-node-monitor@/ff-node-monitor" }, ui = { email_from = "knoten@freifunknord.de", in
stance_article_dative = "der", instance_name = "Freifunk Nord Knotenüberwachung" }, urls = { nodes = "https://mesh.freifunknord.de/data/v2/nodes.json", root = "https://nord.freifunk.net/
node-monitor", sources = "https://github.com/freifunk-saar/ff-node-monitor" } }
thread 'main' panicked at 'app config table has missing or extra value: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "Odd number of digits", key: ["secrets", "a
ction_signing_key"] } }', libcore/result.rs:983:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: ff_node_monitor::config::Config::new
  10: ff_node_monitor::config::fairing::{{closure}}
  11: <rocket::fairing::ad_hoc::AdHoc as rocket::fairing::Fairing>::on_attach
  12: rocket::fairing::fairings::Fairings::attach
  13: rocket::rocket::Rocket::attach
  14: ff_node_monitor::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: <unknown>
```

**Comment by rubo77** [comment]
I figured it out: "Odd number of digits" was the main error message, which could be enhanced to 

> you didn't configure an action_signing_key
