### ISSUE TITLE
multi site support

### ISSUE THREAD

**Issue by rubo77** [freifunk-saar/ff-node-monitor#48]
was müsste man anpassen um mehrere sites zu versorgen?

Ich würde gerne einen dienst für Freifunk Nord und einen für Kiel zur verfügung stellen auf dem selben server. 

Wenn der service läuft, dann müsste man ja eigentlich nur den service kopieren, wobei er eine andere Rocket.toml benutzt.

**Comment by rubo77** [comment]
Und eine andere datenbank anlegen in postgresql

**Comment by rubo77** [comment]
Nach dieser Anleitung hab ich das gemacht, aber dann startet der leider nicht:

```
root@freifunk:/opt/ff-node-monitor-nord# RUST_BACKTRACE=1 sudo -u ff-node-monitor RUST_BACKTRACE=1 /opt/ff-node-monitor/src/target/release/ff-node-monitor
  Configured for development.
    => address: 0.0.0.0
    => port: 8834
    => log: normal
    => workers: 14
    => secret key: provided
    => limits: forms = 32KiB
    => tls: disabled
    => [extra] ff-node-monitor: { secrets = { action_signing_key = "65c07d7aa3b1695d0827be25b29d7aa9040410c02e9646f90897999a5c560d18", postgres_url = "postgres://ff-node-monitor@/ff-node
-monitor-nord", smtp_host = "10.77.77.101" }, ui = { email_from = "freifunk-knotenalarm@lists.in-kiel.de", instance_article_dative = "dem", instance_name = "Freifunk Nord Knotenalarm" },
 urls = { nodes = "https://mesh.freifunknord.de/data/v2/nodes.json", root = "https://freifunk.in-kiel.de/knotenalarm-nord/", sources = "https://github.com/freifunk-saar/ff-node-monitor" 
} }
thread 'main' panicked at 'failed to run migrations: MigrationError(MigrationDirectoryNotFound)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: ff_node_monitor::db_conn::init_db_pool
  10: ff_node_monitor::config::fairing::{{closure}}
  11: <rocket::fairing::ad_hoc::AdHoc as rocket::fairing::Fairing>::on_attach
  12: rocket::fairing::fairings::Fairings::attach 
  13: rocket::rocket::Rocket::attach
  14: ff_node_monitor::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: <unknown>

```

**Comment by rubo77** [comment]
It worked like this:

- copy the whole folder `/opt/ff-node-monitor` into a new location
- delete the whole `src/target/` and `.cargo` folder
- adapt the `Rocket.toml` there

**Comment by RalfJung** [comment]
Uh, you shouldn't have to copy anything other than the service file. Then change
```
WorkingDirectory=/opt/ff-node-monitor/src
```
to another directory. Create symlinks for the `migrations`, `static` and `templates` directories and *copy* the `Rocket.toml` from the original dir, and edit the config.

**Comment by rubo77** [comment]
Ah ok, that was what the error message means:

    thread 'main' panicked at 'failed to run migrations: MigrationError(MigrationDirectoryNotFound)', libcore/result.rs:945:5

**Comment by RalfJung** [comment]
Ah yes, we don't have great error messages currently. They are lots of work. I am juts forwarding the raw information that the underlying libraries are presenting.

**Comment by RalfJung** [comment]
Closing this issue as there is nothing to do on the node-monitor side, as far as I can see. Feel free to open a new issue if you still have questions.

**Comment by rubo77** [comment]
I created a fork for Freifunk-nord with the needed changes in the readme rocket.toml and service file
